plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.ansarweb.hesabbourse'

    compileSdk 36

    defaultConfig {
        applicationId 'ir.ansarweb.hesabbourse'

        minSdk 24
        targetSdk 36

        versionCode 3
        versionName "2.1"
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
